config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'swagger#index'

  # Swagger documentation
  scope :swagger, as: 'swagger' do
    get '/', to: 'swagger#index', as: :root
    get '/data', to: 'swagger#data', as: :data
  end

  draw :authentication

  defaults format: :json do
    # API routes
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/authenticable.rb
# frozen_string_literal: true

module Authenticable
  extend ActiveSupport::Concern

  included do
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable,
           :trackable
  end

  module ClassMethods
    # rubocop:disable Style/RedundantSelf
    def authenticate(email, password)
      user = self.find_for_authentication(email:)
      user&.valid_password?(password) ? user : nil
    end
    # rubocop:enable Style/RedundantSelf
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Authenticable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::API
  include ParameterObjects
end

app/controllers/authenticated_controller.rb
# frozen_string_literal: true

class AuthenticatedController < ApplicationController
  # equivalent of authenticate_user! on devise, but this one will check the oauth token
  before_action :doorkeeper_authorize!

  around_action :switch_locale

  private

  # helper method to access the current user from the token
  def current_user
    @current_user ||= doorkeeper_token.resource_owner
  end

  def switch_locale(&action)
    locale = current_user.try(:locale) || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/concerns/doorkeeper/authorize.rb
# frozen_string_literal: true

module Doorkeeper
  module Authorize
    extend ActiveSupport::Concern

    included do
      before_action :find_doorkeeper_application!

      attr_reader :current_doorkeeper_application
    end

    private

    def find_doorkeeper_application!
      @current_doorkeeper_application = Doorkeeper::Application.find_by(uid: params[:client_id],
                                                                        secret: params[:client_secret])

      render json: invalid_client_response, status: :unauthorized if @current_doorkeeper_application.blank?
    end

    def invalid_client_response
      { errors: [I18n.t('doorkeeper.errors.messages.invalid_client')] }
    end
  end
end

app/controllers/concerns/parameter_objects.rb
# frozen_string_literal: true

module ParameterObjects
  extend ActiveSupport::Concern

  included do
    def pagination_object
      page = params.fetch(:page, 1)
      per_page = params.fetch(:per_page, Kaminari.config.default_per_page)

      CustomObjects::ParameterObject::Pagination.new(page:, per_page:)
    end

    def query_object
      query = params.fetch(:query, {})

      CustomObjects::ParameterObject::Query.new(query:)
    end
  end
end

app/controllers/swagger_controller.rb
# frozen_string_literal: true

class SwaggerController < ApplicationController
  def index
    render html: nil, layout: 'layouts/swagger'
  end

  def data
    swagger_data = SwaggerDocs.swagger_root

    render json: swagger_data, status: :ok
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < ApplicationController
    include Doorkeeper::Authorize

    def create
      operation = Users::Passwords::CreateOperation.new(params: password_params).call

      if operation.success?
        render json: operation.success, status: :ok
      else
        render json: operation.failure, status: :unprocessable_entity
      end
    end

    def update
      operation = Users::Passwords::UpdateOperation.new(params: password_params).call

      if operation.success?
        render json: operation.success, status: :ok
      else
        render json: operation.failure, status: :unprocessable_entity
      end
    end

    private

    def password_params
      params.permit(:email, :reset_password_token, :password, :password_confirmation)
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < ApplicationController
    include Doorkeeper::Authorize

    def create
      operation = Users::Registrations::CreateOperation.new(params: registration_params,
                                                            doorkeeper_application: current_doorkeeper_application).call

      if operation.success?
        render json: operation.success, status: :created
      else
        render json: operation.failure, status: :unprocessable_entity
      end
    end

    private

    def registration_params
      params.permit(:email, :password)
    end
  end
end

app/controllers/users/tokens_controller.rb
# frozen_string_literal: true

module Users
  class TokensController < Doorkeeper::TokensController
    private

    def revocation_error_response
      error_description = I18n.t('doorkeeper.errors.messages.revoke.unauthorized')

      { errors: [error_description] }
    end
  end
end

app/views/layouts/swagger.html.erb
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Swagger UI</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@3.31.1/swagger-ui.css">
    <style>
      html
      {
        box-sizing: border-box;
        overflow: -moz-scrollbars-vertical;
        overflow-y: scroll;
      }

      *,
      *:before,
      *:after
      {
        box-sizing: inherit;
      }

      body
      {
        margin:0;
        background: #fafafa;
      }
    </style>
  </head>

  <body>
    <div id="swagger-ui"></div>

    <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@3.31.1/swagger-ui-bundle.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@3.31.1/swagger-ui-standalone-preset.js"></script>
    <script>
    window.onload = function() {

      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        "dom_id": "#swagger-ui",
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout",
        validatorUrl: "https://validator.swagger.io/validator",
        url: "<%= swagger_data_url %>",
      })

      // End Swagger UI call region
      window.ui = ui
    }
  </script>
  </body>
</html>